image: archlinux
packages:
  - vim
  - neovim
  - ripgrep
  - fzf
  - just
sources:
  - https://git.sr.ht/~adigitoleo/quark.nvim
tasks:
  - test: |
      mkdir -p ~/.config/nvim/plugin
      cp /usr/share/vim/vimfiles/plugin/fzf.vim ~/.config/nvim/plugin
      cd quark.nvim
      just test
